version: "3.7"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    #  - adminer
    environment:
      #MYSQL_HOST: my-mysql
      DB_HOST: db
      DB__PORT: 3306
      #MYSQLX_UNIX_PORT: 33060
      DB_USER: root
      #DATABASE_URL: mysql+pymysql://root:123@my-mysql:3306/my_flask_app
      DB_PASSWORD: 123
      DB_NAME: my_flask_app
      #REDIS_URL: redis://redis-server:6379/0
    links:
      - db
      - redis
    #  - adminer
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    #  - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=my_flask_app

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080