version: "3.7"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - my-mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:123@my-mysql:3306/my_flask_app
      REDIS_URL: redis://redis-server:6379/0
    links:
      - my-mysql
      - redis

  flask_migration:
    build: .
    depends_on:
      my-mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:123@my-mysql:3306/my_flask_app
      REDIS_URL: redis://redis-server:6379/0
    links:
      - my-mysql
      - redis
    command: 
      - flask
      - db
      - upgrade
    restart: on-failure

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  my-mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    #  - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=my_flask_app
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]